import { supabase } from '../lib/AuthContext.jsx';

export const UploadFile = async ({ file }) => {
  const fileExt = file.name.split('.').pop();
  const fileName = `${Math.random().toString(36).substring(2)}-${Date.now()}.${fileExt}`;
  const filePath = `uploads/${fileName}`;

  const { data, error } = await supabase.storage
    .from('files')
    .upload(filePath, file);

  if (error) {
    throw error;
  }

  const { data: publicUrlData } = supabase.storage
    .from('files')
    .getPublicUrl(filePath);

  return { file_url: publicUrlData.publicUrl };
};

export const InvokeLLM = async ({ prompt, system_prompt, response_json_schema, file_urls }) => {
  const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
  if (!GEMINI_API_KEY) {
    throw new Error("Missing VITE_GEMINI_API_KEY in environment variables.");
  }
  
  // Select the model: use flash-latest for everything to avoid Pro quota limits on free-tier keys.
  const model = "gemini-flash-latest";
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`;
  
  const parts = [];
  
  if (file_urls && file_urls.length > 0) {
    for (const fileUrl of file_urls) {
      try {
        const response = await fetch(fileUrl);
        const blob = await response.blob();
        
        // Convert blob to base64
        const base64 = await new Promise((resolve) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result.split(',')[1]);
          reader.readAsDataURL(blob);
        });

        parts.push({
          inlineData: {
            mimeType: blob.type,
            data: base64
          }
        });
      } catch (err) {
        console.error("Failed to fetch file for Gemini:", fileUrl, err);
      }
    }
  }

  parts.push({ text: prompt });

  const body = {
    contents: [
      {
        parts: parts
      }
    ]
  };

  if (system_prompt) {
    body.systemInstruction = {
      parts: [{ text: system_prompt }]
    };
  }

  if (response_json_schema) {
    body.generationConfig = {
      responseMimeType: "application/json",
      responseSchema: response_json_schema
    };
  } else {
    // We expect text/markdown by default if no schema is provided
  }

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  });

  const data = await res.json();
  
  if (!res.ok) {
    throw new Error(`Gemini API Error: ${data.error?.message || res.statusText}`);
  }

  const textResponse = data.candidates?.[0]?.content?.parts?.[0]?.text;
  
  if (!textResponse) {
    throw new Error("No response generated by Gemini");
  }

  if (response_json_schema || body.generationConfig?.responseMimeType === "application/json") {
     try {
       return JSON.parse(textResponse);
     } catch (e) {
       console.warn("Failed to parse Gemini JSON output", textResponse);
       return textResponse;
     }
  }

  return textResponse;
};

export const TranscribeAudio = async ({ audio_url }) => {
  const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
  if (!GEMINI_API_KEY) {
    throw new Error("Missing VITE_GEMINI_API_KEY in environment variables.");
  }

  try {
    const response = await fetch(audio_url);
    const blob = await response.blob();
    
    const base64 = await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result.split(',')[1]);
      reader.readAsDataURL(blob);
    });

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${GEMINI_API_KEY}`;
    const body = {
      contents: [{
        parts: [
          { inlineData: { mimeType: blob.type, data: base64 } },
          { text: "Please accurately transcribe this audio recording. Provide only the transcript." }
        ]
      }]
    };

    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });

    const data = await res.json();
    if (!res.ok) throw new Error(data.error?.message || "Unknown error");

    return { text: data.candidates?.[0]?.content?.parts?.[0]?.text || "" };
  } catch (err) {
    console.error("Transcription failed:", err);
    throw err;
  }
};
